export const posts = [
    {
        id: 1,
        slug: 'titulo-da-postagem',
        title: 'Título da Postagem',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lemons.jpg',
        logo: '/img/clients/_old/bosch.svg',
    },
    {
        id: 2,
        slug: 'titulo-da-postagem-2',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/talk.jpg',
        logo: '/img/clients/_old/getap.svg',
    },
    {
        id: 3,
        slug: 'titulo-da-postagem-3',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/chairs.jpg',
        logo: '/img/clients/_old/john-deere.svg',
    },
    {
        id: 4,
        slug: 'titulo-da-postagem-4',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lighthouse.jpg',
        logo: '/img/clients/_old/sebrae.svg',
    },
    {
        id: 5,
        slug: 'titulo-da-postagem',
        title: 'Título da Postagem',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lemons.jpg',
        logo: '/img/clients/_old/bosch.svg',
    },
    {
        id: 6,
        slug: 'titulo-da-postagem-2',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/talk.jpg',
        logo: '/img/clients/_old/getap.svg',
    },
    {
        id: 7,
        slug: 'titulo-da-postagem-3',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/chairs.jpg',
        logo: '/img/clients/_old/john-deere.svg',
    },
    {
        id: 8,
        slug: 'titulo-da-postagem-4',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lighthouse.jpg',
        logo: '/img/clients/_old/sebrae.svg',
    }
]