export const posts = [
    {
        id: 1,
        slug: 'titulo-da-postagem',
        title: 'Título da Postagem',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lemons.jpg',
        readingTime: '5',
    },
    {
        id: 2,
        slug: 'titulo-da-postagem-2',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/talk.jpg',
        readingTime: '10',
    },
    {
        id: 3,
        slug: 'titulo-da-postagem-3',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/chairs.jpg',
        readingTime: '5',
    },
    {
        id: 4,
        slug: 'titulo-da-postagem-4',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lighthouse.jpg',
        readingTime: '30',
    },
    {
        id: 5,
        slug: 'titulo-da-postagem',
        title: 'Título da Postagem',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lemons.jpg',
        readingTime: '2',
    },
    {
        id: 6,
        slug: 'titulo-da-postagem-2',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/talk.jpg',
        readingTime: '1',
    },
    {
        id: 7,
        slug: 'titulo-da-postagem-3',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/chairs.jpg',
        readingTime: '10',
    },
    {
        id: 8,
        slug: 'titulo-da-postagem-4',
        title: 'Título da Postagem ',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna.',
        image: '/img/lighthouse.jpg',
        readingTime: '7',
    }
]